export const SEARCH_ACTION_TYPES = {
  FETCH_SEARCH_REQUEST: 'search/FETCH_SEARCH_REQUEST',
  FETCH_SEARCH_SUCCESS: 'search/FETCH_SEARCH_SUCCESS',
  FETCH_SEARCH_FAILURE: 'search/FETCH_SEARCH_FAILURE',
  SET_SEARCH_QUERY: 'search/SET_SEARCH_QUERY',
  SAVE_SEARCH_RESULTS: 'search/SAVE_SEARCH_RESULTS',
};
