export const MOVIES_ACTION_TYPES = {
  FETCH_MOVIES_REQUEST: 'movies/FETCH_MOVIES_REQUEST',
  FETCH_MOVIES_SUCCESS: 'movies/FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'movies/FETCH_MOVIES_FAILURE',
  SET_FILTER: 'movies/SET_FILTER',
  SET_SORT_BY: 'movies/SET_SORT_BY',
};
