export const ACTORS_ACTION_TYPES = {
  FETCH_ACTORS_START: 'actors/FETCH_ACTORS_START',
  FETCH_ACTORS_SUCCESS: 'actors/FETCH_ACTORS_SUCCESS',
  FETCH_ACTORS_FAILURE: 'actors/FETCH_ACTORS_FAILURE',
};
